const mongoose = require('mongoose');
const User = require('../models/User');
const Booking = require('../models/Booking');
const Station = require('../models/Station');
const asyncHandler = require('../middleware/asyncHandler');

// @desc    Get dashboard statistics
// @route   GET /api/admin/stats
// @access  Private/Admin
const getAdminStats = asyncHandler(async (req, res) => {
    // Total Users
    const totalUsers = await User.countDocuments({ role: 'user' });

    // Total Stations
    const totalStations = await Station.countDocuments();

    // Total Bookings and status breakdown
    const totalBookings = await Booking.countDocuments();
    const pendingBookings = await Booking.countDocuments({ status: 'Pending' });
    const approvedBookings = await Booking.countDocuments({ status: 'Approved' });
    const rejectedBookings = await Booking.countDocuments({ status: 'Rejected' });
    const completedBookings = await Booking.countDocuments({ status: 'Completed' });

    // Total Revenue (only from confirmed/completed bookings)
    const revenueData = await Booking.aggregate([
        {
            $match: {
                $or: [
                    { status: { $in: ['Confirmed', 'Completed'] } },
                    { paymentStatus: 'Paid' }
                ]
            }
        },
        {
            $group: {
                _id: null,
                totalRevenue: { $sum: '$totalAmount' }
            }
        }
    ]);

    const totalRevenue = revenueData.length > 0 ? revenueData[0].totalRevenue : 0;

    // Today's Revenue
    const startOfToday = new Date();
    startOfToday.setHours(0, 0, 0, 0);
    const endOfToday = new Date();
    endOfToday.setHours(23, 59, 59, 999);

    const todayRevenueData = await Booking.aggregate([
        {
            $match: {
                $and: [
                    {
                        $or: [
                            { status: { $in: ['Confirmed', 'Completed'] } },
                            { paymentStatus: 'Paid' }
                        ]
                    },
                    { updatedAt: { $gte: startOfToday, $lte: endOfToday } }
                ]
            }
        },
        {
            $group: {
                _id: null,
                todayRevenue: { $sum: '$totalAmount' }
            }
        }
    ]);

    const todayRevenue = todayRevenueData.length > 0 ? todayRevenueData[0].todayRevenue : 0;

    res.json({
        success: true,
        message: 'Admin stats fetched',
        data: {
            totalUsers,
            totalStations,
            totalBookings,
            pendingBookings,
            approvedBookings,
            rejectedBookings,
            completedBookings,
            totalRevenue,
            todayRevenue
        }
    });
});

// @desc    Get stats for a specific station
// @route   GET /api/admin/station/:id/stats
// @access  Private/Admin
const getStationStats = asyncHandler(async (req, res) => {
    const stationId = req.params.id;

    const station = await Station.findById(stationId);
    if (!station) {
        res.status(404);
        throw new Error('Station not found');
    }

    // Total Bookings for this station
    const totalBookings = await Booking.countDocuments({ station: stationId });

    // Revenue generated by this station
    const revenueData = await Booking.aggregate([
        {
            $match: {
                station: new mongoose.Types.ObjectId(stationId),
                status: { $in: ['Confirmed', 'Completed'] }
            }
        },
        {
            $group: {
                _id: null,
                totalRevenue: { $sum: '$totalAmount' }
            }
        }
    ]);

    const totalRevenue = revenueData.length > 0 ? revenueData[0].totalRevenue : 0;

    // Active Bookings (confirmed status and date/time not passed)
    const activeBookings = await Booking.countDocuments({
        station: stationId,
        status: 'Confirmed',
    });

    // Available slots (simplified: total slots - active bookings for "now")
    // In a real app, this would be time-slot based.
    const availableSlots = Math.max(0, station.totalSlots - activeBookings);

    res.json({
        success: true,
        message: 'Station stats fetched',
        data: {
            stationName: station.name,
            totalBookings,
            totalRevenue,
            activeBookings,
            availableSlots
        }
    });
});

// @desc    Get all users (Admin View)
// @route   GET /api/admin/users
// @access  Private/Admin
const getUsers = asyncHandler(async (req, res) => {
    const role = req.query.role;
    let query = {};
    
    if (role) {
        query.role = role;
    }

    const users = await User.find(query).select('-password');

    res.json({
        success: true,
        message: 'Users fetched',
        data: users
    });
});

// @desc    Get all bookings (Admin View)
// @route   GET /api/admin/bookings
// @access  Private/Admin
const getAllBookings = asyncHandler(async (req, res) => {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const skip = (page - 1) * limit;

    const { status, search } = req.query;
    let query = {};

    // Status filter
    if (status && status !== 'All') {
        query.status = status;
    }

    // Search filter
    if (search) {
        // We'll search by vehicle number first
        // For User/Station name, we might need a more complex query since they are refs
        // But for now, let's support vehicleNumber and we'll handle User/Station name if possible
        // Actually, searching by populated fields in Mongo usually requires aggregation or separate queries
        // Let's keep it simple: search by vehicleNumber or just return and filter in frontend for small datasets
        // Or better, find userIds/stationIds that match search and use $in
        
        const matchingUsers = await User.find({ name: { $regex: search, $options: 'i' } }).select('_id');
        const matchingStations = await Station.find({ name: { $regex: search, $options: 'i' } }).select('_id');
        
        query.$or = [
            { vehicleNumber: { $regex: search, $options: 'i' } },
            { user: { $in: matchingUsers.map(u => u._id) } },
            { station: { $in: matchingStations.map(s => s._id) } }
        ];
    }

    const totalBookings = await Booking.countDocuments(query);
    const totalPages = Math.ceil(totalBookings / limit);

    const bookings = await Booking.aggregate([
        { $match: query },
        {
            $lookup: {
                from: 'users',
                localField: 'user',
                foreignField: '_id',
                as: 'user'
            }
        },
        { $unwind: '$user' },
        {
            $lookup: {
                from: 'stations',
                localField: 'station',
                foreignField: '_id',
                as: 'station'
            }
        },
        { $unwind: { path: '$station', preserveNullAndEmptyArrays: true } },
        {
            $lookup: {
                from: 'payments',
                localField: '_id',
                foreignField: 'booking',
                as: 'payment'
            }
        },
        { $unwind: { path: '$payment', preserveNullAndEmptyArrays: true } },
        {
            $project: {
                'user.password': 0,
                'user.role': 0,
                'user.createdAt': 0,
                'user.updatedAt': 0,
                'user.__v': 0
            }
        },
        { $sort: { createdAt: -1 } },
        { $skip: skip },
        { $limit: limit }
    ]);

    res.json({
        success: true,
        message: 'Bookings fetched',
        data: {
            bookings,
            totalBookings,
            totalPages,
            currentPage: page
        }
    });
});

// @desc    Get analytics trend data
// @route   GET /api/admin/analytics
// @access  Private/Admin
const getAnalytics = asyncHandler(async (req, res) => {
    // 1. Bookings Trend (Last 7 days)
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    sevenDaysAgo.setHours(0, 0, 0, 0);

    const bookingsTrend = await Booking.aggregate([
        {
            $match: {
                createdAt: { $gte: sevenDaysAgo }
            }
        },
        {
            $group: {
                _id: { $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } },
                count: { $sum: 1 }
            }
        },
        { $sort: { _id: 1 } }
    ]);

    // 2. Revenue Trend (Last 7 days)
    const revenueTrend = await Booking.aggregate([
        {
            $match: {
                $and: [
                    {
                        $or: [
                            { status: { $in: ['Confirmed', 'Completed'] } },
                            { paymentStatus: 'Paid' }
                        ]
                    },
                    { updatedAt: { $gte: sevenDaysAgo } }
                ]
            }
        },
        {
            $group: {
                _id: { $dateToString: { format: "%Y-%m-%d", date: "$updatedAt" } },
                amount: { $sum: "$totalAmount" }
            }
        },
        { $sort: { _id: 1 } }
    ]);

    // 3. Status Distribution
    const statusDistribution = await Booking.aggregate([
        {
            $group: {
                _id: "$status",
                count: { $sum: 1 }
            }
        }
    ]);

    res.json({
        success: true,
        message: 'Analytics fetched',
        data: {
            bookingsTrend,
            revenueTrend,
            statusDistribution
        }
    });
});

module.exports = {
    getAdminStats,
    getStationStats,
    getUsers,
    getAllBookings,
    getAnalytics
};
